apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-deployment
spec:
  selector:
      matchLabels:
        app: employee
  replicas: 1
  template:
    metadata:
      labels:
        app: employee
    spec:
      containers:
        - name: employee
          image: "public.ecr.aws/y0e8u1e1/springboot-service:codepipelinebuild$DATE"
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8080
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_INITDB_DATABASE
            - name: MONGO_INITDB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: MONGO_INITDB_HOST
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-auth
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-auth
                  key: MONGO_INITDB_ROOT_PASSWORD
              
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
  labels:
    app: employee
spec:
  type: ClusterIp
  ports:
    - name: https
      port: 8080
      targetPort: 8080
  selector:
    app: employee
          
