apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo:latest
        name: mongodb
        imagePullPolicy: "IfNotPresent"           
        ports:
        - containerPort: 27017
        envFrom:
          - configMapRef:
              name: mongodb-config
          - secretRef:
              name: mongo-auth
        volumeMounts:
        - name: mongodb
          mountPath: /var/lib/mongodb/data
      volumes:
      - name: mongodb
        persistentVolumeClaim:
          claimName: mongodb-pv-claim
